name: Bug report
description: Reportar un error
labels: ["bug"]
body:
  - type: input
    id: context
    attributes: { label: Contexto, placeholder: "Ruta, endpoint, caso de uso" }
    validations: { required: true }
  - type: textarea
    id: steps
    attributes: { label: Pasos para reproducir, placeholder: "1. ... 2. ... 3. ..." }
    validations: { required: true }
  - type: input
    id: expected
    attributes: { label: Esperado }
    validations: { required: true }
  - type: input
    id: actual
    attributes: { label: Actual }
    validations: { required: true }
  - type: dropdown
    id: severity
    attributes: { label: Severidad, options: ["S1 crítica", "S2 alta", "S3 media", "S4 baja"] }
    validations: { required: true }
  - type: textarea
    id: logs
    attributes: { label: Logs / capturas }
